filtered:
  topic:
    name: filtered
greeting:
  topic:
    name: greeting
kafka:
  backoff:
    interval: 9000
    max_failure: 5
long:
  message:
    topic:
      name: longMessage
message:
  topic:
    name: baeldung
monitor:
  consumer:
    simulate: true
  kafka:
    bootstrap:
      config: localhost:9092
    consumer:
      groupid: baeldungGrp
      groupid.simulate: baeldungGrpSimulate
  producer:
    simulate: true
  topic:
    name: baeldung
multi:
  type:
    topic:
      name: multitype
partitioned:
  topic:
    name: partitioned
spring:
  kafka:
    bootstrap-servers: localhost:9093
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
test:
  topic: testtopic1