spring:
  rabbitmq:
    host: 101.43.146.222
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        modelId-out-0:
          destination: model-id
        model-in-0:
          destination: model
      function:
        definition: modelId;model
  zipkin:
    baseUrl: http://101.43.146.222:9411/
