token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJ6bGVubm9uQDE2My5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZ2VvaXBfY291bnRyeSI6IkRFIn0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vYXV0aCI6eyJ1c2VyX2lkIjoidXNlci1UOHNPamJLUEd3c2g5REFsb2VKRnlTRVIifSwiaXNzIjoiaHR0cHM6Ly9hdXRoMC5vcGVuYWkuY29tLyIsInN1YiI6ImF1dGgwfDYzOWE3ZjM0MTA1MDkxMWI2MDE2MTZhMCIsImF1ZCI6WyJodHRwczovL2FwaS5vcGVuYWkuY29tL3YxIiwiaHR0cHM6Ly9vcGVuYWkub3BlbmFpLmF1dGgwYXBwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2Nzc4MzMzOTYsImV4cCI6MTY3OTA0Mjk5NiwiYXpwIjoiVGRKSWNiZTE2V29USHROOTVueXl3aDVFNHlPbzZJdEciLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG1vZGVsLnJlYWQgbW9kZWwucmVxdWVzdCBvcmdhbml6YXRpb24ucmVhZCBvZmZsaW5lX2FjY2VzcyJ9.X8YqCZb9xJZCSRspYlYKtxVV4-BHY5UeJa17FBaC35XECssuE29r_PIYx3uOELS85oUN5XxyuPMkU2mUJ8jhFf009lDW-nkHm9bgROxaFbSfVsdylpHkVPo2I0irQkUN34qnoksLWkkZ0R4R00zUcey_IlMdXIBCQ0G5g3mF439VUwHJWDHAw5kd053TQAxPBdx543jC0eniXvI87K88vVCFmCHztJc7i7RKM222R5gi94p25im9IqZhWxk1jHgIZFfoOANHucQJQ3_wbGutgBze-YWFNH_Q9oTiJbqSnSSb5PjUmFN4PI0mWk7q1kzp_eV6fzAt-Ba1obS4-o1h1Q
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chatgpt?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}-${server.port}
        service-name: chatgpt-service
        health-check-path: /actuator/health
        health-check-interval: 30s
server:
  port: 7999
