spring:
  application:
    name: cloud-task-service
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_task?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
  batch:
    jdbc:
      initialize-schema: always
logging:
  level.org.springframework.cloud.task: DEBUG
