server:
  port: 7100
spring:
  cloud:
    service-registry:
      enabled: false
    consul:
      host: 101.43.146.222
      port: 8500
      enabled: true
  zipkin:
    baseUrl: http://101.43.146.222:9411/
