
spring:
  application:
    name: chatgpt-model-service
  datasource:
    url: jdbc:mysql://localhost:3306/chatgpt?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
  rabbitmq:
    host: 101.43.146.222
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      modelId-in-0:
        destination: model-id
      model-out-0:
        destination: model
      function:
        definition: modelId;model
  zipkin:
    baseUrl: http://101.43.146.222:9411/

server:
  port: 7888
