
spring:
  application:
    name: chatgpt-model-service
  datasource:
    url: jdbc:mysql://localhost:3306/chatgpt?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
  rabbitmq:
    host: 10.10.80.104
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      sendModelId-in-0:
        destination: get-model-info
      function:
        definition: sendModelId
server:
  port: 7888
