server:
  port: 7005
spring:
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/lennonn/spring-cloud-config.git
          search-paths: /
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        instance-id: ${spring.application.name}-${server.port}
        health-check-path: /actuator/health
        health-check-interval: 30s
    bus:
      enabled: true
      refresh:
        enabled: true
      trace:
        enabled: true
  application:
    name: cloud-bus-service
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
   org.springframework.cloud.bus: debug
debug: true